### PR TITLE
Upgrade httpoison

### PR DESCRIPTION
**Pull request by rsierra**
First of all, thanks for the work.

I'm currently using this lib and I have some issues with httpoison 0.11 dependencies (hackney, unicode_util_compat...) in the last versions of Erlang and Elixir that are solved in 0.13.

I just added the new version to the mix file and updated the test results with the new data returned from Google API.

I will be glad if you consider to allow this version in a new release.

Let me know if you need any change. Thanks again!

### CODE REVIEW

**Comment by sntran** [comment]
Hi there,

Thanks for the changes!

I checked the changes between 0.11 and 0.13 and didn't see any big changes. If there are, please let me know. Otherwise, I'm okay with switching to 0.13 directly instead of keeping two versions.

**Comment by rsierra** [comment]
My problem is this issue with hackney

https://github.com/benoitc/hackney/issues/416

If I tracked the versions in the right way, it is solved un 1.8, that is satisfied by httpoison 0.13.

I will change to 0.13 then.

**Comment by sntran** [comment]
Sounds good. Do you mind if I squash and merge?

**Comment by rsierra** [comment]
Feel free 😃

**Comment by sntran** [comment]
Thank you!

**Comment by rsierra** [comment]
Thank you too!

**Pull request merged**
