### PR TITLE
Refactor timezone/2

### PR DESCRIPTION
**Pull request by uesteibar**
This is the refactor proposed in the [timezone PR](https://github.com/sntran/ex_maps/pull/10#discussion_r158564010).

Thanks for the quick feedback! 😃

### CODE REVIEW

**Comment by sntran** [comment]
Thanks!

**Comment by tapajos** [comment]
Any idea of when it will be released?

**Comment by sntran** [comment]
I'm on the road, and will release a new version right after.

**Comment by tapajos** [comment]
@sntran thank you, sir.

**Pull request merged**
